
FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime


WORKDIR /app


RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY detect_server.py .
COPY 1280best.pt .

EXPOSE 8000

CMD ["python", "detect_server.py"]